name: Build Flutter Android APK

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests as well

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      # Checkout the latest code
      - uses: actions/checkout@v4

      # Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Install the Eclipse Temurin distribution of JDK
          java-version: '17'       # Install JDK 17

      # Set up Flutter with master channel
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'master'  # Use Flutter master channel as preferred
          channel: 'master'           # Set the channel to master

      # Install Flutter dependencies
      - run: flutter pub get

      # Build APK for Android
      - run: flutter build apk --release

      # Upload APK artifact to GitHub (optional)
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
