name: Build Flutter iOS App for Simulator

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests as well

jobs:
  build_ios_simulator:
    runs-on: macos-latest  # iOS builds require macOS

    steps:
      # Checkout the latest code
      - uses: actions/checkout@v4

      # Set up Flutter with master channel
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'master'  # Use Flutter master channel as preferred
          channel: 'master'          # Set the channel to master

      # Precache iOS engine artifacts
      - name: Precache iOS artifacts
        run: flutter precache --ios

      # Install Flutter dependencies
      - run: flutter pub get

      # Install CocoaPods dependencies
      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install
          
      # Build iOS app for simulator (no code signing required)
      - run: flutter build ios --simulator

      # Upload iOS build artifact (optional)
      - name: Upload App Bundle
        uses: actions/upload-artifact@v3
        with:
          name: ios-app
          path: build/ios/**/*.app  # The simulator build is in .app format
