name: Deploy Flutter Web to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the latest code
      - uses: actions/checkout@v4

      # Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.5.2'  # Set your desired Flutter version here

      # Install Flutter dependencies
      - run: flutter pub get

      # Build Flutter Web
      - run: flutter build web --release

      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SWAPPY_PIN }}
          channelId: live
          projectId: swappy-pin
          target: swappy-pin
        env:
          FIREBASE_DEPLOY_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
